<<<<<<< HEAD
github: [thinkyhead]
patreon: thinkyhead
custom: ["https://www.thinkyhead.com/donate-to-marlin"]
=======
custom: http://www.thinkyhead.com/donate-to-marlin
>>>>>>> 1314b31d97bba8cd74c6625c47176d4692f57790
